#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    p = 0
    l = 0
    q = 0
    for i in arr:
        if i > 0:
            p += 1
        elif i < 0:
            l += 1
        else:
            q += 1
    
    total = len(arr)
    
    positive_ratio = p / total
    negative_ratio = l / total
    zero_ratio = q / total
    
    print(f'{positive_ratio:.6f}')
    print(f'{negative_ratio:.6f}')
    print(f'{zero_ratio:.6f}')

if __name__ == '__main__':        
    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))
    plusMinus(arr)
