#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    h = s[0]+s[1]
    m = s[3]+s[4]
    d = s[6]+s[7]
        
        
    if s[8] == chr(80) and s[9] == chr(77):
        if int(h) != 12:
            h = str(int(h) + 12)
    elif s[8] == 'A' and s[9] == 'M':
        if int(h) == 12:
            h = str(int(h) - 12)
            h = '0'+'0'
    
    return f'{h}:{m}:{d}'
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
